zzimcar:
  http:
    auth-token-header:
      name: X-API-Key
    auth-token: 109353c6-6432-4acf-8e77-ef842f64a664

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jpabookshop
    username: Kim
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true